spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:oracle://51.141.108.8:1521/STUDENT_KOROLEV
    username: STUDENT_KOROLEV
    password: LJyi75Rt
  flyway:
    baseline-on-migrate: true